version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: hackaton_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/data
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://hackaton_ttx2_user:Urr39QwFluPWl38Pq1ckurpZyaQje2Tu@dpg-cvrrrcili9vc739n1of0-a:5432/hackaton_ttx2

    depends_on:
      - db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgis/postgis:15-3.3
    container_name: hackaton_db
    environment:
      - POSTGRES_DB=hackaton
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
